### ISSUE TITLE
Create & design templates for user documentation

### ISSUE THREAD

**Issue by maxprogram** [atlastory/api#9]
All documentation is stored in `/docs` as Markdown files. The `home#index` controller renders the Markdown files into HTML for final viewing.

- [x] Create basic design/styling template to view docs
- [x] Integrate with controller
- [x] Write basic examples for getting Model data, GeoJSONs, Changeset uploads, etc.

**Comment by maxprogram** [comment]
Fixed with f76b6c8d6d434aa6caeb470f1ef9fa4dccbab4aa
